# Copyright (c) 2018-2022 Margarita Colberg
# SPDX-License-Identifier: BSD-3-Clause

name: build and test

on:
  push:
    paths:
      - .github/workflows/build.yml
      - CMakeLists.txt
      - Makefile
      - cmake/**
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - debug
          - release

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get -y -qq update

      - run: sudo apt-get -y -qq install build-essential cmake ninja-build libhdf5-dev libboost-program-options-dev libboost-test-dev libboost-filesystem-dev

      - run: make ${{ matrix.config }}
        env:
          # treat compiler warnings as errors
          CXXFLAGS: -Werror
          # show compiler commands (requires CMake 3.14)
          VERBOSE: 1
          # https://packages.ubuntu.com/focal/amd64/libhdf5-dev/filelist
          CMAKE_INCLUDE_PATH: /usr/include/hdf5/serial
          CMAKE_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu/hdf5/serial

      - run: cd ${{ matrix.config }} && ctest -V
